export const dataBar = [
	{ name: 'sda', value: 400 },
	{ name: 'asd', value: -300 },
	{ name: 'das', value: 200 },
	{ name: 'wqw', value: -278 },
	{ name: 'qwe', value: 189 },
	{ name: 'wqe', value: -239 },
	{ name: 'xzx', value: 349 },
];

export const dataLine = [
	{ name: 'wqe', value: 600 },
	{ name: 'da', value: 450 },
	{ name: 'li', value: 200 },
	{ name: 'd', value: 150 },
	{ name: 'as', value: 150 },
	{ name: 'ad', value: 160 },
	{ name: 'zxc', value: 160 },
	{ name: 'wqe', value: 600 },
	{ name: 'da', value: 450 },
	{ name: 'li', value: 200 },
	{ name: 'd', value: 150 },
	{ name: 'as', value: 150 },
];

export const dayOptions = [
	{ label: '7D', value: '7D' },
	{ label: '30D', value: '30D' },
	{ label: '90D', value: '90D' },
];

export const depositsWithdrawalsOptions = [
	{ label: 'All', value: 'ALL' },
	{ label: 'Deposit', value: 'DEPOSIT' },
	{ label: 'Withdrawal', value: 'WITHDRAW' },
];

export const DistributionOptions = [
	{ label: 'All', value: 'ALL' },
	{ label: 'Referral commission', value: 'REFERRER_REBATE' },
	{ label: 'Referee rebate', value: 'REFEREE_REBATE' },
	{ label: 'Broker fee', value: 'BROKER_FEE' },
];

export const fundingOptions = [
	{ label: 'All', value: 'ALL' },
	{ label: '1000BONK', value: 'PERP_1000BONK_USDC' },
	{ label: '1000FLOKI', value: 'PERP_1000FLOKI_USDC' },
	{ label: '1000PEPE', value: 'PERP_1000PEPE_USDC' },
	{ label: 'AAVE', value: 'PERP_AAVE_USDC' },
	{ label: 'APT', value: 'PERP_APT_USDC' },
	{ label: 'ARB', value: 'PERP_ARB_USDC' },
	{ label: 'AR', value: 'PERP_AR_USDC' },
	{ label: 'AVAX', value: 'PERP_AVAX_USDC' },
	{ label: 'BCH', value: 'PERP_BCH_USDC' },
	{ label: 'BLAST', value: 'PERP_BLAST_USDC' },
	{ label: 'BLUR', value: 'PERP_BLUR_USDC' },
	{ label: 'BNB', value: 'PERP_BNB_USDC' },
	{ label: 'CHZ', value: 'PERP_CHZ_USDC' },
	{ label: 'CRV', value: 'PERP_CRV_USDC' },
	{ label: 'DOGE', value: 'PERP_DOGE_USDC' },
	{ label: 'DOGS', value: 'PERP_DOGS_USDC' },
	{ label: 'ENA', value: 'PERP_ENA_USDC' },
	{ label: 'ETHFI', value: 'PERP_ETHFI_USDC' },
	{ label: 'ETH', value: 'PERP_ETH_USDC' },
	{ label: 'FIL', value: 'PERP_FIL_USDC' },
	{ label: 'FTM', value: 'PERP_FTM_USDC' },
	{ label: 'INJ', value: 'PERP_INJ_USDC' },
	{ label: 'IO', value: 'PERP_IO_USDC' },
	{ label: 'JUP', value: 'PERP_JUP_USDC' },
	{ label: 'LDO', value: 'PERP_LDO_USDC' },
	{ label: 'LINK', value: 'PERP_LINK_USDC' },
	{ label: 'MERL', value: 'PERP_MERL_USDC' },
	{ label: 'MEW', value: 'PERP_MEW_USDC' },
	{ label: 'MKR', value: 'PERP_MKR_USDC' },
	{ label: 'NOT', value: 'PERP_NOT_USDC' },
	{ label: 'OMNI', value: 'PERP_OMNI_USDC' },
	{ label: 'ONDO', value: 'PERP_ONDO_USDC' },
	{ label: 'OP', value: 'PERP_OP_USDC' },
	{ label: 'ORDER', value: 'PERP_ORDER_USDC' },
	{ label: 'ORDI', value: 'PERP_ORDI_USDC' },
	{ label: 'PEOPLE', value: 'PERP_PEOPLE_USDC' },
	{ label: 'POL', value: 'PERP_POL_USDC' },
	{ label: 'PONKE', value: 'PERP_PONKE_USDC' },
	{ label: 'POPCAT', value: 'PERP_POPCAT_USDC' },
	{ label: 'REZ', value: 'PERP_REZ_USDC' },
	{ label: 'SEI', value: 'PERP_SEI_USDC' },
	{ label: 'SOL', value: 'PERP_SOL_USDC' },
	{ label: 'STG', value: 'PERP_STG_USDC' },
	{ label: 'STRK', value: 'PERP_STRK_USDC' },
	{ label: 'SUI', value: 'PERP_SUI_USDC' },
	{ label: 'TIA', value: 'PERP_TIA_USDC' },
	{ label: 'TON', value: 'PERP_TON_USDC' },
	{ label: 'TRX', value: 'PERP_TRX_USDC' },
	{ label: 'WIF', value: 'PERP_WIF_USDC' },
	{ label: 'WLD', value: 'PERP_WLD_USDC' },
	{ label: 'WOO', value: 'PERP_WOO_USDC' },
	{ label: 'W', value: 'PERP_W_USDC' },
	{ label: 'XRP', value: 'PERP_XRP_USDC' },
	{ label: 'ZK', value: 'PERP_ZK_USDC' },
	{ label: 'ZRO', value: 'PERP_ZRO_USDC' },
];
