export const dataBar = [
	{ name: 'sda', value: 400 },
	{ name: 'asd', value: -300 },
	{ name: 'das', value: 200 },
	{ name: 'wqw', value: -278 },
	{ name: 'qwe', value: 189 },
	{ name: 'wqe', value: -239 },
	{ name: 'xzx', value: 349 },
];

export const dataLine = [
	{ name: 'wqe', value: 600 },
	{ name: 'da', value: 450 },
	{ name: 'li', value: 200 },
	{ name: 'd', value: 150 },
	{ name: 'as', value: 150 },
	{ name: 'ad', value: 160 },
	{ name: 'zxc', value: 160 },
	{ name: 'wqe', value: 600 },
	{ name: 'da', value: 450 },
	{ name: 'li', value: 200 },
	{ name: 'd', value: 150 },
	{ name: 'as', value: 150 },
];

export const dayOptions = [
	{ label: '7D', value: '7D' },
	{ label: '30D', value: '30D' },
	{ label: '90D', value: '90D' },
];

export const depositsWithdrawalsOptions = [
	{ label: 'All', value: 'ALL' },
	{ label: 'Deposit', value: 'DEPOSIT' },
	{ label: 'Withdrawal', value: 'WITHDRAW' },
];

export const DistributionOptions = [
	{ label: 'All', value: 'ALL' },
	{ label: 'Referral commission', value: 'REFERRER_REBATE' },
	{ label: 'Referee rebate', value: 'REFEREE_REBATE' },
	{ label: 'Broker fee', value: 'BROKER_FEE' },
];

export const fundingOptions = [
	{ label: 'All', value: 'ALL' },
	{ label: 'Referral commission', value: 'PERP_1000BONK_USDC' },
	{ label: 'Referee rebate', value: 'PERP_1000FLOKI_USDC' },
	{ label: 'Broker fee', value: 'PERP_1000PEPE_USDC' },
	{ label: 'Referral commission', value: 'PERP_AAVE_USDC' },
	{ label: 'Referee rebate', value: 'PERP_APT_USDC' },
	{ label: 'Broker fee', value: 'PERP_ARB_USDC' },
	{ label: 'Referral commission', value: 'PERP_AR_USDC' },
	{ label: 'Referee rebate', value: 'PERP_AVAX_USDC' },
	{ label: 'Broker fee', value: 'PERP_BCH_USDC' },
	{ label: 'Referral commission', value: 'PERP_BLAST_USDC' },
	{ label: 'Referee rebate', value: 'PERP_BLUR_USDC' },
	{ label: 'Broker fee', value: 'PERP_BNB_USDC' },
	{ label: 'Referral commission', value: 'PERP_CHZ_USDC' },
	{ label: 'Referee rebate', value: 'PERP_CRV_USDC' },
	{ label: 'Broker fee', value: 'PERP_DOGE_USDC' },
	{ label: 'Referral commission', value: 'PERP_DOGS_USDC' },
	{ label: 'Referee rebate', value: 'PERP_ENA_USDC' },
	{ label: 'Broker fee', value: 'PERP_ETHFI_USDC' },
	{ label: 'Referral commission', value: 'PERP_ETH_USDC' },
	{ label: 'Referee rebate', value: 'PERP_FIL_USDC' },
	{ label: 'Broker fee', value: 'PERP_FTM_USDC' },
	{ label: 'Referral commission', value: 'PERP_INJ_USDC' },
	{ label: 'Referee rebate', value: 'PERP_IO_USDC' },
	{ label: 'Broker fee', value: 'PERP_JUP_USDC' },
	{ label: 'Referral commission', value: 'PERP_LDO_USDC' },
	{ label: 'Referee rebate', value: 'PERP_LINK_USDC' },
	{ label: 'Broker fee', value: 'PERP_MERL_USDC' },
	{ label: 'Referral commission', value: 'PERP_MEW_USDC' },
	{ label: 'Referee rebate', value: 'PERP_MKR_USDC' },
	{ label: 'Broker fee', value: 'PERP_MKR_USDC' },
	{ label: 'Referral commission', value: 'PERP_NOT_USDC' },
	{ label: 'Referee rebate', value: 'PERP_OMNI_USDC' },
	{ label: 'Broker fee', value: 'PERP_ONDO_USDC' },
	{ label: 'Referral commission', value: 'PERP_OP_USDC' },
	{ label: 'Referee rebate', value: 'PERP_ORDER_USDC' },
	{ label: 'Broker fee', value: 'PERP_ORDI_USDC' },
	{ label: 'Referral commission', value: 'PERP_PEOPLE_USDC' },
	{ label: 'Referee rebate', value: 'PERP_POL_USDC' },
	{ label: 'Broker fee', value: 'PERP_PONKE_USDC' },
	{ label: 'Referral commission', value: 'PERP_POPCAT_USDC' },
	{ label: 'Referee rebate', value: 'PERP_REZ_USDC' },
	{ label: 'Broker fee', value: 'PERP_SEI_USDC' },
	{ label: 'Referral commission', value: 'PERP_SOL_USDC' },
	{ label: 'Referee rebate', value: 'PERP_STG_USDC' },
	{ label: 'Broker fee', value: 'PERP_STRK_USDC' },
	{ label: 'Referral commission', value: 'PERP_SUI_USDC' },
	{ label: 'Referee rebate', value: 'PERP_TIA_USDC' },
	{ label: 'Broker fee', value: 'PERP_TON_USDC' },
	{ label: 'Referral commission', value: 'PERP_TRX_USDC' },
	{ label: 'Referee rebate', value: 'PERP_WIF_USDC' },
	{ label: 'Broker fee', value: 'PERP_WLD_USDC' },
	{ label: 'Referral commission', value: 'PERP_WOO_USDC' },
	{ label: 'Referee rebate', value: 'PERP_W_USDC' },
	{ label: 'Broker fee', value: 'PERP_XRP_USDC' },
	{ label: 'Referral commission', value: 'PERP_ZK_USDC' },
	{ label: 'Referee rebate', value: 'PERP_ZRO_USDC' },
];
